package jet.shareplot.persistence.ejb.share;

import javax.ejb.EJBException;
import javax.ejb.EJBObject;

import java.rmi.RemoteException;

/**
 * Remote interface for the bean 
 *
 * Generated by JetTools, do not edit this file directly.
 */
public interface ShareRemote extends EJBObject {
    

    /**
     * @return Long
     * @throws EJBException
     * @throws RemoteException
     */
    public Long getIdShare() throws EJBException, RemoteException;
    /**
     * @param idShare
     * @throws EJBException
     * @throws RemoteException
     */
    public void setIdShare(Long idShare) throws EJBException, RemoteException;
    

    /**
     * @return String
     * @throws EJBException
     * @throws RemoteException
     */
    public String getCodeISIN() throws EJBException, RemoteException;
    /**
     * @param codeISIN
     * @throws EJBException
     * @throws RemoteException
     */
    public void setCodeISIN(String codeISIN) throws EJBException, RemoteException;
    

    /**
     * @return String
     * @throws EJBException
     * @throws RemoteException
     */
    public String getCodeYahoo() throws EJBException, RemoteException;
    /**
     * @param codeYahoo
     * @throws EJBException
     * @throws RemoteException
     */
    public void setCodeYahoo(String codeYahoo) throws EJBException, RemoteException;
    

    /**
     * @return String
     * @throws EJBException
     * @throws RemoteException
     */
    public String getDescription() throws EJBException, RemoteException;
    /**
     * @param description
     * @throws EJBException
     * @throws RemoteException
     */
    public void setDescription(String description) throws EJBException, RemoteException;
    

    /**
     * @return Long
     * @throws EJBException
     * @throws RemoteException
     */
    public Long getIdPortfolio() throws EJBException, RemoteException;
    /**
     * @param idPortfolio
     * @throws EJBException
     * @throws RemoteException
     */
    public void setIdPortfolio(Long idPortfolio) throws EJBException, RemoteException;
    

    /**
     * @return String
     * @throws EJBException
     * @throws RemoteException
     */
    public String getName() throws EJBException, RemoteException;
    /**
     * @param name
     * @throws EJBException
     * @throws RemoteException
     */
    public void setName(String name) throws EJBException, RemoteException;
    

    /**
     * @param codeISIN
     * @param codeYahoo
     * @param description
     * @param idPortfolio
     * @param name
     * @throws EJBException
     * @throws RemoteException
     */
    public void update( String codeISIN, String codeYahoo, String description, Long idPortfolio, String name) throws EJBException, RemoteException;
}
