package jet.shareplot.persistence.ejb.share;

import java.rmi.RemoteException;
import java.util.Collection;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.ejb.CreateException;
import javax.ejb.EJBException;
import javax.ejb.EntityBean;
import javax.ejb.EntityContext;
import javax.ejb.FinderException;
import javax.ejb.RemoveException;

/**
 * Class of the bean.
 *
 * Generated by JetTools, do not edit this file directly.
 */
public final class ShareBean implements EntityBean {

    /**
     * <code>serialVersionUID</code>.
     */
    private static final long serialVersionUID = -1939421298L;

    private transient EntityContext entityContext;

    // fields must remain public as it is part of the EJB specifications
    /**
     * Field idShare of type Long, database type INTEGER of length 10.
     */
    public Long idShare;
    /**
     * Field codeISIN of type String, database type VARCHAR of length 45.
     */
    public String codeISIN;
    /**
     * Field codeYahoo of type String, database type VARCHAR of length 45.
     */
    public String codeYahoo;
    /**
     * Field description of type String, database type VARCHAR of length 4000.
     */
    public String description;
    /**
     * Field name of type String, database type VARCHAR of length 255.
     */
    public String name;

    /**
     * Get the value for the field idShare.
     *
     * @return Long value for the field idShare
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    @Nullable
    public Long getIdShare() throws EJBException {
        return this.idShare;

    }
    /**
     * Set the value for the field idShare.
     *
     * @param idShare value for the field idShare
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    public void setIdShare(@Nullable final Long idShare) throws EJBException {
        this.idShare = idShare;
    }

    /**
     * Get the value for the field codeISIN.
     *
     * @return String value for the field codeISIN
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    @Nullable
    public String getCodeISIN() throws EJBException {
        return this.codeISIN;

    }
    /**
     * Set the value for the field codeISIN.
     *
     * @param codeISIN value for the field codeISIN
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    public void setCodeISIN(@Nullable final String codeISIN) throws EJBException {
        this.codeISIN = codeISIN;
    }

    /**
     * Get the value for the field codeYahoo.
     *
     * @return String value for the field codeYahoo
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    @Nullable
    public String getCodeYahoo() throws EJBException {
        return this.codeYahoo;

    }
    /**
     * Set the value for the field codeYahoo.
     *
     * @param codeYahoo value for the field codeYahoo
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    public void setCodeYahoo(@Nullable final String codeYahoo) throws EJBException {
        this.codeYahoo = codeYahoo;
    }

    /**
     * Get the value for the field description.
     *
     * @return String value for the field description
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    @Nullable
    public String getDescription() throws EJBException {
        return this.description;

    }
    /**
     * Set the value for the field description.
     *
     * @param description value for the field description
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    public void setDescription(@Nullable final String description) throws EJBException {
        this.description = description;
    }

    /**
     * Get the value for the field name.
     *
     * @return String value for the field name
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    @Nullable
    public String getName() throws EJBException {
        return this.name;

    }
    /**
     * Set the value for the field name.
     *
     * @param name value for the field name
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    public void setName(@Nullable final String name) throws EJBException {
        this.name = name;
    }


    /**
     * ejbCreate method.
     *
     * @param idShare value for the field idShare
     * @param codeISIN value for the field codeISIN
     * @param codeYahoo value for the field codeYahoo
     * @param description value for the field description
     * @param name value for the field name
     * @return java.lang.Object bean primary key
     * @throws CreateException Thrown by the method to indicate a failure during the creation.
     */
    @SuppressWarnings("hiding")
    @Nullable
    public java.lang.Object ejbCreate(final Long idShare, final String codeISIN, final String codeYahoo, final String description, final String name) throws CreateException {
        this.idShare = idShare;
        this.codeISIN = codeISIN;
        this.codeYahoo = codeYahoo;
        this.description = description;
        this.name = name;
        return null;
    }

    /**
     * ejbPostCreate method.
     *
     * @param idShare value for the field idShare
     * @param codeISIN value for the field codeISIN
     * @param codeYahoo value for the field codeYahoo
     * @param description value for the field description
     * @param name value for the field name
     * @throws CreateException Thrown by the method to indicate a failure during the creation.
     */
    @SuppressWarnings("hiding")
    public void ejbPostCreate(final Long idShare, final String codeISIN, final String codeYahoo, final String description, final String name) throws CreateException {
        assert this.entityContext != null : "this.entityContext can not be null";

        jet.container.managers.jdbc.interfaces.AutoGeneratedPrimaryKey _pk = (jet.container.managers.jdbc.interfaces.AutoGeneratedPrimaryKey) this.entityContext.getPrimaryKey();
        Number _number = (Number) _pk.getAutoGeneratedPrimaryKey();
        this.idShare = Long.valueOf(_number.longValue());
    }

    /**
     * Find a record by its primary key.
     *
     * @param pkField primary key
     * @return java.lang.Object primary key object
     * @throws FinderException The exception is used as a standard application-level exception to report a failure to find the requested EJB object(s).
     */
    @Nonnull
    public java.lang.Object ejbFindByPrimaryKey(@Nonnull final java.lang.Object pkField) throws FinderException {
        if (pkField instanceof jet.container.managers.jdbc.interfaces.AutoGeneratedPrimaryKey) {
            jet.container.managers.jdbc.interfaces.AutoGeneratedPrimaryKey _pk = (jet.container.managers.jdbc.interfaces.AutoGeneratedPrimaryKey) pkField;
            this.idShare = (Long) _pk.getAutoGeneratedPrimaryKey();
        }
        return pkField;
    }

    /**
     * Update record.
     *
     * @param codeISIN value for the field codeISIN
     * @param codeYahoo value for the field codeYahoo
     * @param description value for the field description
     * @param name value for the field name
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     */
    @SuppressWarnings("hiding")
    public void update(final String codeISIN, final String codeYahoo, final String description, final String name) throws EJBException {
        // in the case of a m-n table this method may be empty, as pk fields can not be updated
        this.codeISIN = codeISIN;
        this.codeYahoo = codeYahoo;
        this.description = description;
        this.name = name;
    }

    /**
     * Finder method.
     *
     * @return Collection of records
     * @throws FinderException The exception is used as a standard application-level exception to report a failure to find the requested EJB object(s).
     */
    public Collection<ShareRemote> ejbFindAll() throws FinderException {
        return null;
    }

    /**
     * Finder method.
     *
     * @param sqlWhereClause String value for finder argument sqlWhereClause
     * @param sqlArguments Object[] value for finder argument sqlArguments
     * @return Collection of records
     * @throws FinderException The exception is used as a standard application-level exception to report a failure to find the requested EJB object(s).
     */
    public Collection<ShareRemote> ejbFindByPreparedSQLQuery(final String sqlWhereClause, final Object[] sqlArguments) throws FinderException {
        return null;
    }


    @Override
    @SuppressWarnings("unused")
    public void ejbActivate() throws RemoteException {
        // do nothing
    }

    @Override
    @SuppressWarnings("unused")
    public void ejbLoad() throws RemoteException {
        // do nothing
    }

    @Override
    @SuppressWarnings("unused")
    public void ejbPassivate() throws RemoteException {
        // do nothing
    }

    @Override
    @SuppressWarnings("unused")
    public void ejbRemove() throws RemoteException, RemoveException {
        // do nothing
    }

    @Override
    @SuppressWarnings("unused")
    public void ejbStore() throws RemoteException {
        // do nothing
    }

    @Override
    @SuppressWarnings("unused")
    public void setEntityContext(@Nullable final EntityContext context) throws RemoteException {
        this.entityContext = context;
    }

    @Override
    @SuppressWarnings("unused")
    public void unsetEntityContext() throws RemoteException {
        this.entityContext = null;
    }
}
