package jet.shareplot.persistence.ejb.share;

import org.eclipse.jdt.annotation.Nullable;
import javax.ejb.EJBException;
import javax.ejb.EJBObject;

import java.rmi.RemoteException;

/**
 * Remote interface for the bean.
 *
 * Generated by JetTools, do not edit this file directly.
 */
public interface ShareRemote extends EJBObject {


    /**
     * Get the value for the field idShare.
     *
     * @return Long value for the field idShare
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    @Nullable Long getIdShare() throws EJBException, RemoteException;
    
    /**
     * Set the value for the field idShare.
     *
     * @param idShare value for the field idShare
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    void setIdShare(final @Nullable Long idShare) throws EJBException, RemoteException;


    /**
     * Get the value for the field codeISIN.
     *
     * @return String value for the field codeISIN
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    @Nullable String getCodeISIN() throws EJBException, RemoteException;
    
    /**
     * Set the value for the field codeISIN.
     *
     * @param codeISIN value for the field codeISIN
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    void setCodeISIN(final @Nullable String codeISIN) throws EJBException, RemoteException;


    /**
     * Get the value for the field codeYahoo.
     *
     * @return String value for the field codeYahoo
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    @Nullable String getCodeYahoo() throws EJBException, RemoteException;
    
    /**
     * Set the value for the field codeYahoo.
     *
     * @param codeYahoo value for the field codeYahoo
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    void setCodeYahoo(final @Nullable String codeYahoo) throws EJBException, RemoteException;


    /**
     * Get the value for the field description.
     *
     * @return String value for the field description
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    @Nullable String getDescription() throws EJBException, RemoteException;
    
    /**
     * Set the value for the field description.
     *
     * @param description value for the field description
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    void setDescription(final @Nullable String description) throws EJBException, RemoteException;


    /**
     * Get the value for the field name.
     *
     * @return String value for the field name
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    @Nullable String getName() throws EJBException, RemoteException;
    
    /**
     * Set the value for the field name.
     *
     * @param name value for the field name
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    void setName(final @Nullable String name) throws EJBException, RemoteException;


    /**
     * Update record.
     *
     * @param codeISIN value for the field codeISIN
     * @param codeYahoo value for the field codeYahoo
     * @param description value for the field description
     * @param name value for the field name
     * @throws EJBException Thrown by the method to indicate a failure caused by a system-level error.
     * @throws RemoteException Thrown if one of a number of communication-related exceptions occurs during the execution of the remote method call.
     */
    void update(final @Nullable String codeISIN, final @Nullable String codeYahoo, final @Nullable String description, final @Nullable String name) throws EJBException, RemoteException;
}
