package jet.shareplot.persistence.ejb.sharevalue;

import javax.ejb.EJBException;
import javax.ejb.EJBObject;

import java.rmi.RemoteException;

/**
 * Remote interface for the bean 
 *
 * Generated by JetTools, do not edit this file directly.
 */
public interface ShareValueRemote extends EJBObject {
    

    /**
     * @return Long
     * @throws EJBException
     * @throws RemoteException
     */
    public Long getIdShareValue() throws EJBException, RemoteException;
    /**
     * @param idShareValue
     * @throws EJBException
     * @throws RemoteException
     */
    public void setIdShareValue(Long idShareValue) throws EJBException, RemoteException;
    

    /**
     * @return Long
     * @throws EJBException
     * @throws RemoteException
     */
    public Long getIdShare() throws EJBException, RemoteException;
    /**
     * @param idShare
     * @throws EJBException
     * @throws RemoteException
     */
    public void setIdShare(Long idShare) throws EJBException, RemoteException;
    

    /**
     * @return java.math.BigDecimal
     * @throws EJBException
     * @throws RemoteException
     */
    public java.math.BigDecimal getValue() throws EJBException, RemoteException;
    /**
     * @param value
     * @throws EJBException
     * @throws RemoteException
     */
    public void setValue(java.math.BigDecimal value) throws EJBException, RemoteException;
    

    /**
     * @return java.util.Date
     * @throws EJBException
     * @throws RemoteException
     */
    public java.util.Date getValueDate() throws EJBException, RemoteException;
    /**
     * @param valueDate
     * @throws EJBException
     * @throws RemoteException
     */
    public void setValueDate(java.util.Date valueDate) throws EJBException, RemoteException;
    

    /**
     * @param idShare
     * @param value
     * @param valueDate
     * @throws EJBException
     * @throws RemoteException
     */
    public void update( Long idShare, java.math.BigDecimal value, java.util.Date valueDate) throws EJBException, RemoteException;
}
