package jet.shareplot.persistence.finder.portfolio;

import java.util.HashMap;
import java.util.Map;

import jet.framework.nuts.select.FinderMethod;

/**
 * Class for the findAll FinderMethod object for the Portfolio component.
 *
 * SQL Query : 
 *
 * Generated by JetTools, do not edit this file directly.
 */
public class Portfolio_FindAll0 implements FinderMethod {

    private static final long serialVersionUID = 993423458L;


    @Override
    public String getFinderName() {
        return "findAll";
    }

    @Override
    public Map<String, Object> getArguments() {
        return new HashMap<String, Object>();
    }
}
