package jet.shareplot.persistence.ejb.sharequantity;

import javax.ejb.EJBException;
import javax.ejb.EJBObject;

import java.rmi.RemoteException;

/**
 * Remote interface for the bean 
 *
 * Generated by JetTools, do not edit this file directly.
 */
public interface ShareQuantityRemote extends EJBObject {
    

    /**
     * @return Long
     * @throws EJBException
     * @throws RemoteException
     */
    public Long getIdShareQuantity() throws EJBException, RemoteException;
    /**
     * @param idShareQuantity
     * @throws EJBException
     * @throws RemoteException
     */
    public void setIdShareQuantity(Long idShareQuantity) throws EJBException, RemoteException;
    

    /**
     * @return Long
     * @throws EJBException
     * @throws RemoteException
     */
    public Long getIdShare() throws EJBException, RemoteException;
    /**
     * @param idShare
     * @throws EJBException
     * @throws RemoteException
     */
    public void setIdShare(Long idShare) throws EJBException, RemoteException;
    

    /**
     * @return java.util.Date
     * @throws EJBException
     * @throws RemoteException
     */
    public java.util.Date getValueDate() throws EJBException, RemoteException;
    /**
     * @param valueDate
     * @throws EJBException
     * @throws RemoteException
     */
    public void setValueDate(java.util.Date valueDate) throws EJBException, RemoteException;
    

    /**
     * @return String
     * @throws EJBException
     * @throws RemoteException
     */
    public String getChangeType() throws EJBException, RemoteException;
    /**
     * @param changeType
     * @throws EJBException
     * @throws RemoteException
     */
    public void setChangeType(String changeType) throws EJBException, RemoteException;
    

    /**
     * @param idShare
     * @param valueDate
     * @param changeType
     * @throws EJBException
     * @throws RemoteException
     */
    public void update( Long idShare, java.util.Date valueDate, String changeType) throws EJBException, RemoteException;
}
