package jet.shareplot.persistence.finder.share;

import java.util.HashMap;
import java.util.Map;

import jet.framework.nuts.select.FinderMethod;

/**
 * Class for the findByPortfolio FinderMethod object for the Share component.
 *
 * SQL Query : where idPortfolio = ?
 *
 * Generated by JetTools, do not edit this file directly.
 */
public class Share_FindByPortfolio1 implements FinderMethod {
    Long idPortfolio = null;

    /**
     * Set idPortfolio argument value
     * @param idPortfolio argument value
     */
    public void setIdPortfolio(final Long idPortfolio) {
        this.idPortfolio = idPortfolio;
    }

    @Override
    public String getFinderName() {
        return "findByPortfolio";
    }

    @Override
    public Map<String, Object> getArguments() {
        final Map<String, Object> args = new HashMap<String, Object>();
        args.put("idPortfolio", this.idPortfolio);
        return args;
    }
}
