package jet.shareplot.ac.bo.merged.fullsharevalue;

import jet.framework.util.exception.FormatedJetException;
import jet.framework.util.pojo2.AbstractResourceNotification.NOTIFICATION_TYPE;
import jet.framework.util.pojo2.JFBusinessCallableHelper;
import jet.framework.util.pojo2.JFBusinessDeleteCallable;
import jet.framework.util.pojo2.JFBusinessErrorHelper;
import jet.framework.util.pojo2.JFBusinessItem;
import jet.framework.util.pojo2.JFBusinessSaveCallable;
import jet.shareplot.ac.SelectStoreApplicationComponent;
import jet.shareplot.persistence.pojo.merged.FullShareValueItem;
import jet.util.models.interfaces.Model;

/**
 * Sample bo class, extending the pojo FullShareValueItem.
 *
 * Generated by JetTools, you can edit this file directly, once created it will not be overwritten
 *
 * @author JetToolsFramework
 */
public class FullShareValue extends FullShareValueItem implements JFBusinessItem, JFBusinessErrorHelper {

    private static final long serialVersionUID = 1L;

    // TODO set localized keys for error dialogs
    private static final String CAN_NOT_SAVE_KEY = "";
    private static final String CAN_NOT_DELETE_KEY = "";
    private static final String NOT_VALID_KEY = "";

    private final FullShareValueApplicationComponent fullShareValueAC;

    /**
     * Constructor, build an empty fullShareValue
     *
     * @param fullShareValueAC the fullShareValue application component
     *
     * @see Model
     * @see FullShareValueApplicationComponent
     */
    public FullShareValue(final FullShareValueApplicationComponent fullShareValueAC) {
        super();
        this.fullShareValueAC = fullShareValueAC;
    }

    /**
     * Constructor, build a fullShareValue from a Model
     *
     * @param model the model representing a fullShareValue entry in the table FullShareValue
     * @param fullShareValueAC the fullShareValue application component
     *
     * @see Model
     * @see FullShareValueApplicationComponent
     */
    public FullShareValue(final Model model, final FullShareValueApplicationComponent fullShareValueAC) {
        super(model);
        this.fullShareValueAC = fullShareValueAC;
    }

    /**
     * Copy constructor, build a fullShareValue as a copy of another fullShareValue
     *
     * @param fullShareValue the fullShareValue to copy
     */
    public FullShareValue(final FullShareValue fullShareValue) {
        super(fullShareValue);
        this.fullShareValueAC = fullShareValue.fullShareValueAC;
    }

    /**
     * @return <code>true</code> if this fullShareValue is valid and can be saved.
     * @see JFBusinessItem
     */
    @Override
    public final boolean isValid() {
        // TODO add extra validations here
        return !isNotNullableNull();
    }

    /**
     * @return <code>true</code> if this fullShareValue is new.
     * @see JFBusinessItem
     */
    @Override
    public final boolean isNew() {
        // TODO implement this method
        return false;
    }

    /**
     * Register the object in the database.
     * The store will only be done if the fullShareValue is valid.
     * It will updated if it already exists and create it if not.
     *
     * @throws FormatedJetException
     * @see FormatedJetException
     * @see #isNew()
     * @see #isValid()
     * @see JFBusinessItem
     */
    @Override
    public final void save() throws FormatedJetException {
        if (isValid()) {
            final FullShareValueResource resource;
            if (isNew()) {
                resource = new FullShareValueResource(this.fullShareValueAC, this, NOTIFICATION_TYPE.CREATE);
            } else {
                resource = new FullShareValueResource(this.fullShareValueAC, this, NOTIFICATION_TYPE.UPDATE);
            }

            final JFBusinessSaveCallable callable = new JFBusinessSaveCallable(this.fullShareValueAC, SelectStoreApplicationComponent.FULLSHAREVALUE_STORE, this);
            JFBusinessCallableHelper.storeChange(this.fullShareValueAC, callable, CAN_NOT_SAVE_KEY, this);

            resource.notifyResource();
        } else {
            throw getFormatedJetException(NOT_VALID_KEY, null);
        }
    }

    /**
     * Remove the object from the database.
     * It will be deleted if it already exists.
     *
     * @throws FormatedJetException
     * @see FormatedJetException
     * @see #isNew()
     * @see JFBusinessItem
     */
    @Override
    public final void delete() throws FormatedJetException {
        if (!isNew()) {
            final JFBusinessDeleteCallable callable = new JFBusinessDeleteCallable(this.fullShareValueAC, SelectStoreApplicationComponent.FULLSHAREVALUE_STORE, this);
            JFBusinessCallableHelper.storeChange(this.fullShareValueAC, callable, CAN_NOT_DELETE_KEY, this);

            final FullShareValueResource resource = new FullShareValueResource(this.fullShareValueAC, this, NOTIFICATION_TYPE.DELETE);
            resource.notifyResource();
        }
    }

    /**
     * Produce error for save / delete
     *
     * @return FormatedJetException
     * @see FormatedJetException
     * @see JFBusinessErrorHelper
     * @see #save()
     * @see #delete()
     */
    @Override
    public FormatedJetException getFormatedJetException(final String key, final Exception e) {
        final Object[] args = {};
        return new FormatedJetException(null, key, args, e);
    }

}
