package jet.shareplot.persistence.imutval.portfolio;

import org.eclipse.jdt.annotation.NonNull;

import jet.framework.util.pojo2.validator.ImutValidator;
import jet.framework.util.pojo2.validator.ValidationException;

import jet.shareplot.persistence.imut.portfolio.PortfolioShareImut;

/**
 * Immutable object for the PortfolioShare Data Model.
 *
 * Generated by JetTools, this file will not be overwriten once created.
 *
 * @author JetToolsFramework
 */
public final class PortfolioShareImutVal implements ImutValidator<PortfolioShareImut> {

    /**
     * Constructor.
     */
    public PortfolioShareImutVal() {
        // nothing to do
    }

    @Override
    public void validate(@NonNull final PortfolioShareImut imutObject) throws ValidationException {
        // TODO fill in validation rules here
    }
}
