package jet.shareplot.persistence.dse;

import java.rmi.RemoteException;
import java.util.concurrent.Callable;

import javax.annotation.Nonnull;
import javax.ejb.FinderException;
import javax.ejb.ObjectNotFoundException;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import jet.framework.manager.datamodel.interfaces.AbstractDataSourceExecutor2;
import jet.framework.manager.datamodel.interfaces.DataModelConverter2;
import jet.framework.manager.datamodel.interfaces.DataModelRootNode;
import jet.framework.util.JetConstants;
import jet.framework.util.jta.JETDuplicateKeyException;
import jet.shareplot.persistence.dmc.ShareDMC;
import jet.shareplot.persistence.ejb.share.ShareHome;
import jet.shareplot.persistence.ejb.share.ShareRemote;
import jet.shareplot.persistence.pojo.ShareItem;
import jet.util.models.interfaces.Model;
import jet.util.throwable.JETException;

/**
 * Share DataSourceExecutor2.
 *
 * Generated by JetTools, do not edit this file directly.
 */
public final class ShareDSE extends AbstractDataSourceExecutor2<ShareHome, ShareRemote> {

    private static final long serialVersionUID = -1939421298L;
    private transient ShareHome ejbHome;
    private transient DataModelConverter2<ShareRemote> dataModelConverter;

    @Override
    public void updateFromDataModel(@Nonnull final Model dataModel) throws JETException, ObjectNotFoundException {
        final Callable<Object> callable = new Callable<Object>() {
            @Override
            public Object call() throws Exception {
                final ShareRemote ejbObject = getObjectFromStore(dataModel);
                getDataModelConverter().writeDataModelToObject(dataModel, ejbObject);
                return null;
            }
        };

        callUpdateTransaction(callable);

        // reset the dirty flag, record has just been written to the db, can not be dirty
        if (dataModel instanceof DataModelRootNode) {
            final DataModelRootNode dmrn = (DataModelRootNode) dataModel;
            dmrn.resetDirtyFlag();
        }
    }

    @Override
    public void createFromDataModel(@Nonnull final Model dataModel) throws JETException, JETDuplicateKeyException {
        final Callable<Object> callable = new Callable<Object>() {
            @Override
            public Object call() throws Exception {
                final ShareItem shareItem = new ShareItem(dataModel);

                final ShareHome shareHome = getEJBHome();
                final ShareRemote shareRemote = shareHome.create(shareItem.getIdShare(), shareItem.getCodeISIN(), shareItem.getCodeYahoo(), shareItem.getDescription(), shareItem.getName());

                // has autoincrement PK, must update
                shareItem.get_IdShare_Model().setNodeValue(shareRemote.getIdShare());

                return null;
            }
        };

        callCreateTransaction(callable);

        // reset the dirty flag, record has just been written to the db, can not be dirty
        if (dataModel instanceof DataModelRootNode) {
            final DataModelRootNode dmrn = (DataModelRootNode) dataModel;
            dmrn.resetDirtyFlag();
        }
    }

    @Override
    public void removeFromDataModel(@Nonnull final Model dataModel) throws JETException, ObjectNotFoundException {
        final Callable<Object> callable = new Callable<Object>() {
            @Override
            public Object call() throws Exception {
                final ShareRemote shareRemote = getObjectFromStore(dataModel);
                shareRemote.remove();
                return null;
            }
        };

        callUpdateTransaction(callable);

        // set the dirty flag, record has just been deleted from the db, can only be dirty
        if (dataModel instanceof DataModelRootNode) {
            final DataModelRootNode dmrn = (DataModelRootNode) dataModel;
            dmrn.setDirtyFlag();
        }

        // if has autoincrement PK, must reset pk to null
        final ShareItem shareItem = new ShareItem(dataModel);
        shareItem.get_IdShare_Model().setNodeValue(null);
    }

    @Override
    @Nonnull
    public ShareHome getEJBHome() {
        ShareHome result = this.ejbHome;
        if (result == null) {
            try {
                result = this.ejbHome = (ShareHome) new InitialContext().lookup(JetConstants.EJB_CONTEXT + ShareHome.BEAN_NAME);
            } catch (final NamingException e) {
                throw new IllegalArgumentException("Unable to locate EJB Home : " + ShareHome.BEAN_NAME, e);
            }
            if (result == null) {
                throw new IllegalArgumentException("Unknown EJB : " + ShareHome.BEAN_NAME);
            }
        }
        return result;
    }

    @Override
    @Nonnull
    public DataModelConverter2<ShareRemote> getDataModelConverter() {
        DataModelConverter2<ShareRemote> result = this.dataModelConverter;
        if (result == null) {
            result = this.dataModelConverter = new ShareDMC();
        }

        return result;
    }

    /**
     * Get object from the persistent store corresponding to the data Model. Depending on the implementation
     * it may not be necessary to provide a full data Model.
     * <p>
     * This should be used with care as this may entail Transaction problems, depending on the underlying persistance layer.
     * </p>
     *
     * @param dataModel Model identifying the object to retrieve
     * @return E Persistent object corresponding to the Model
     * @throws JETException Thrown if there was an error whilst retrieving the object
     * @throws ObjectNotFoundException Thrown if there is no corresponding object
     */
    @Nonnull
    private ShareRemote getObjectFromStore(@Nonnull final Model dataModel) throws JETException, ObjectNotFoundException {
        assert dataModel != null : "Can not delete null model";

        final ShareItem shareItem = new ShareItem(dataModel);
        final ShareHome shareHome = getEJBHome();

        ShareRemote shareRemote;
        try {
            // As it come from the database, it should not be possible that field(s) in the PK are null.
            shareRemote = shareHome.findByPrimaryKey(shareItem.getIdShare());
            assert shareRemote != null;
        } catch (final RemoteException e) {
            throw new JETException(e.getMessage(), e);
        } catch (final ObjectNotFoundException e) {
            throw e;
        } catch (final FinderException e) {
            throw new JETException(e.getMessage(), e);
        }

        return shareRemote;
    }
}
