package jet.shareplot.persistence.imutval;

import org.eclipse.jdt.annotation.NonNull;

import jet.framework.util.pojo2.validator.ImutValidator;
import jet.framework.util.pojo2.validator.ValidationException;

import jet.shareplot.persistence.imut.ShareValueImut;

/**
 * Immutable object for the ShareValue Data Model.
 *
 * Generated by JetTools, this file will not be overwriten once created.
 *
 * @author JetToolsFramework
 */
public final class ShareValueImutVal implements ImutValidator<ShareValueImut> {

    /**
     * Constructor.
     */
    public ShareValueImutVal() {
        // nothing to do
    }

    @Override
    public void validate(@NonNull final ShareValueImut imutObject) throws ValidationException {
        // TODO fill in validation rules here
    }
}
