package jet.shareplot.persistence.dmc;

import java.rmi.RemoteException;

import javax.ejb.EJBException;

import jet.framework.manager.datamodel.interfaces.DataModelConverter2;
import jet.shareplot.persistence.ejb.share.ShareRemote;
import jet.shareplot.persistence.pojo.ShareItem;
import jet.util.models.interfaces.Model;
import jet.util.throwable.JETException;

/**
 * Share DataModelConverter2
 *
 * Generated by JetTools, do not edit this file directly.
 */
public class ShareDMC implements DataModelConverter2<ShareRemote> {

    private static final long serialVersionUID = -1265738400L;

    @Override
    public Model readDataModelFromObject(final ShareRemote dataObject) throws JETException {
        final ShareItem item = new ShareItem();

        try {
            item.get_IdShare_Model().setNodeValue(dataObject.getIdShare());
            item.get_CodeISIN_Model().setNodeValue(dataObject.getCodeISIN());
            item.get_CodeYahoo_Model().setNodeValue(dataObject.getCodeYahoo());
            item.get_Description_Model().setNodeValue(dataObject.getDescription());
            item.get_IdPortfolio_Model().setNodeValue(dataObject.getIdPortfolio());
            item.get_Name_Model().setNodeValue(dataObject.getName());
        } catch (final EJBException e) {
            throw new JETException("EJBException while reading from ShareRemote.", e);
        } catch (final RemoteException e) {
            throw new JETException("RemoteException while reading from ShareRemote.", e);
        }

        return item.get_Model();
    }

    @Override
    public void writeDataModelToObject(final Model dataModel, final ShareRemote dataObject) throws JETException {
        final ShareItem item = new ShareItem(dataModel);

        try {
            // do not update pk fields
            // note: all item set pk methods are note public, so use the setNodeValue method on model
            item.get_IdShare_Model().setNodeValue(item.getIdShare());
        } catch (final EJBException e) {
            throw new JETException("EJBException while writing to ShareRemote.", e);
        }
    }

}
