package jet.shareplot.persistence.dmc;

import java.rmi.RemoteException;

import javax.ejb.EJBException;

import jet.framework.manager.datamodel.interfaces.DataModelConverter2;
import jet.shareplot.persistence.ejb.sharevalue.ShareValueRemote;
import jet.shareplot.persistence.pojo.ShareValueItem;
import jet.util.models.interfaces.Model;
import jet.util.throwable.JETException;

/**
 * ShareValue DataModelConverter2
 *
 * Generated by JetTools, do not edit this file directly.
 */
public class ShareValueDMC implements DataModelConverter2<ShareValueRemote> {

    private static final long serialVersionUID = 1303211696L;

    @Override
    public Model readDataModelFromObject(final ShareValueRemote shareValueRemote) throws JETException {
        final ShareValueItem shareValueItem = new ShareValueItem();

        try {
            shareValueItem.get_IdShareValue_Model().setNodeValue(shareValueRemote.getIdShareValue());
            shareValueItem.get_IdShare_Model().setNodeValue(shareValueRemote.getIdShare());
            shareValueItem.get_Value_Model().setNodeValue(shareValueRemote.getValue());
            shareValueItem.get_ValueDate_Model().setNodeValue(shareValueRemote.getValueDate());
        } catch (final EJBException e) {
            throw new JETException("EJBException while reading from ShareValueRemote.", e);
        } catch (final RemoteException e) {
            throw new JETException("RemoteException while reading from ShareValueRemote.", e);
        }

        return shareValueItem.get_Model();
    }

    @Override
    public void writeDataModelToObject(final Model dataModel, final ShareValueRemote shareValueRemote) throws JETException {
        final ShareValueItem shareValueItem = new ShareValueItem(dataModel);

        try {
            // do not update pk fields
            shareValueRemote.setIdShare(shareValueItem.getIdShare());
            shareValueRemote.setValue(shareValueItem.getValue());
            shareValueRemote.setValueDate(shareValueItem.getValueDate());
        } catch (final EJBException e) {
            throw new JETException("EJBException while writing to ShareValueRemote.", e);
        } catch (final RemoteException e) {
            throw new JETException("RemoteException while writing to ShareValueRemote.", e);
        }
    }

}
