SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `Share` ADD COLUMN `codeYahoo` VARCHAR(45) NULL DEFAULT NULL  AFTER `codeISIN` , 
    CHANGE COLUMN `code` `codeISIN` VARCHAR(45) NULL DEFAULT NULL  ;

ALTER TABLE `ShareQuantity` ADD COLUMN `description` VARCHAR(1000) NULL DEFAULT NULL  AFTER `valueDate` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
