SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `Share` DROP COLUMN `entryFee` , 
    DROP COLUMN `purchasePrice` , 
    DROP COLUMN `datePurchase` ;

ALTER TABLE `ShareQuantity` CHANGE COLUMN `shareValue` `changeValue` DECIMAL(12,2) NOT NULL  , 
    CHANGE COLUMN `shareQuantity` `changeQuantity` DECIMAL(12,2) NOT NULL  ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
