SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `shareplot`.`ShareValue` DROP FOREIGN KEY `fk_ShareValue_Share` ;

ALTER TABLE `shareplot`.`ShareValue` CHANGE COLUMN `isShare` `idShare` INT(11) NOT NULL  , 
  ADD CONSTRAINT `fk_ShareValue_Share`
  FOREIGN KEY (`idShare` )
  REFERENCES `shareplot`.`Share` (`idShare` )
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE `shareplot`.`Portfolio` CHANGE COLUMN `isFake` `isFake` CHAR(1) NOT NULL DEFAULT 'N'  ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
