
USE BSJA_04


/****** Object:  Copy data to Table [ShareValue]    Generated by JetToolsFramework  ******/
DELETE FROM [ShareValue]

INSERT INTO [ShareValue] (
 [idShareValue] , [isShare] , [value] , [valueDate] )
SELECT
 [idShareValue] , [isShare] , [value] , [valueDate] FROM BSJA_03..[ShareValue]


/****** Object:  Copy data to Table [Share]    Generated by JetToolsFramework  ******/
DELETE FROM [Share]

INSERT INTO [Share] (
 [idShare] , [code] , [description] , [idPortfolio] , [name] )
SELECT
 [idShare] , [code] , [description] , [idPortfolio] , [name] FROM BSJA_03..[Share]


/****** Object:  Copy data to Table [ShareQuantity]    Generated by JetToolsFramework  ******/
DELETE FROM [ShareQuantity]

INSERT INTO [ShareQuantity] (
 [idShareQuantity] , [changeFee] , [changeQuantity] , [changeType] , [changeValue] , [idShare] , [valueDate] )
SELECT
 [idShareQuantity] , [changeFee] , [changeQuantity] , [changeType] , [changeValue] , [idShare] , [valueDate] FROM BSJA_03..[ShareQuantity]


/****** Object:  Copy data to Table [Portfolio]    Generated by JetToolsFramework  ******/
DELETE FROM [Portfolio]

INSERT INTO [Portfolio] (
 [idPortfolio] , [isFake] , [name] )
SELECT
 [idPortfolio] , [isFake] , [name] FROM BSJA_03..[Portfolio]

